# Creates a double-clickable Windows launcher using the CRAN shiny.exe package.
# Run once with: Rscript create_launcher.R

script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
project_dir <- if (length(script_arg)) {
  dirname(normalizePath(sub("^--file=", "", script_arg[[1L]]), winslash = "/"))
} else {
  normalizePath(getwd(), winslash = "/")
}

if (!requireNamespace("shiny.exe", quietly = TRUE)) {
  stop(
    "Install shiny.exe first with install.packages('shiny.exe'), then run this script again.",
    call. = FALSE
  )
}

old_directory <- setwd(project_dir)
on.exit(setwd(old_directory), add = TRUE)

shiny.exe::shiny.exe(
  appName = "USGS_3DEP_Lidar_Explorer",
  host = "127.0.0.1",
  appDir = project_dir
)

# shiny.exe generates machine-specific absolute paths. Replace those generated
# files with portable equivalents while retaining shiny.exe::hostWin as the
# launcher. Both files determine their locations when they are run.
writeLines(
  c(
    "# Generated by create_launcher.R; keep beside app.R.",
    "source_file <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)",
    "script_arg <- grep('^--file=', commandArgs(trailingOnly = FALSE), value = TRUE)",
    "script_file <- if (!is.null(source_file)) source_file else if (length(script_arg)) sub('^--file=', '', script_arg[[1L]]) else file.path(getwd(), 'USGS_3DEP_Lidar_Explorer.R')",
    "app_dir <- dirname(normalizePath(script_file, winslash = '/', mustWork = TRUE))",
    "shiny.exe::hostWin(",
    "  appDir = app_dir,",
    "  port = getOption('shiny.port'),",
    "  launch.browser = getOption('shiny.launch.browser', TRUE),",
    "  host = '127.0.0.1'",
    ")"
  ),
  file.path(project_dir, "USGS_3DEP_Lidar_Explorer.R")
)

writeLines(
  c(
    "@echo off",
    "setlocal",
    "cd /d \"%~dp0\"",
    "set \"RSCRIPT=\"",
    "for /f \"delims=\" %%I in ('where Rscript.exe 2^>nul') do if not defined RSCRIPT set \"RSCRIPT=%%I\"",
    "if not defined RSCRIPT for /f \"delims=\" %%I in ('dir /b /s \"%LOCALAPPDATA%\\Programs\\R\\R-*\\bin\\Rscript.exe\" 2^>nul') do if not defined RSCRIPT set \"RSCRIPT=%%I\"",
    "if not defined RSCRIPT for /f \"delims=\" %%I in ('dir /b /s \"%LOCALAPPDATA%\\Programs\\R\\R-*\\bin\\x64\\Rscript.exe\" 2^>nul') do if not defined RSCRIPT set \"RSCRIPT=%%I\"",
    "if not defined RSCRIPT for /f \"delims=\" %%I in ('dir /b /s \"%ProgramFiles%\\R\\R-*\\bin\\Rscript.exe\" 2^>nul') do if not defined RSCRIPT set \"RSCRIPT=%%I\"",
    "if not defined RSCRIPT for /f \"delims=\" %%I in ('dir /b /s \"%ProgramFiles%\\R\\R-*\\bin\\x64\\Rscript.exe\" 2^>nul') do if not defined RSCRIPT set \"RSCRIPT=%%I\"",
    "if not defined RSCRIPT (",
    "  echo Rscript.exe was not found. Install R and ensure Rscript is on PATH.",
    "  pause",
    "  exit /b 1",
    ")",
    "\"%RSCRIPT%\" \"%~dp0USGS_3DEP_Lidar_Explorer.R\"",
    "pause"
  ),
  file.path(project_dir, "USGS_3DEP_Lidar_Explorer.bat")
)

message("Created a portable USGS_3DEP_Lidar_Explorer.bat. Double-click it to start the app.")
