# Generated by create_launcher.R; keep beside app.R.
source_file <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
script_arg <- grep('^--file=', commandArgs(trailingOnly = FALSE), value = TRUE)
script_file <- if (!is.null(source_file)) source_file else if (length(script_arg)) sub('^--file=', '', script_arg[[1L]]) else file.path(getwd(), 'USGS_3DEP_Lidar_Explorer.R')
app_dir <- dirname(normalizePath(script_file, winslash = '/', mustWork = TRUE))
shiny.exe::hostWin(
  appDir = app_dir,
  port = getOption('shiny.port'),
  launch.browser = getOption('shiny.launch.browser', TRUE),
  host = '127.0.0.1'
)
